# frozen_string_literal: true

source 'https://rubygems.org'

gem 'cookstyle'
gem 'csv'
gem 'highline'
gem 'inspec', '>= 6.8.1'
gem 'inspec-bin'
gem 'inspec-core'
gem 'json'
gem 'kitchen-ansible'
gem 'kitchen-inspec'
gem 'kitchen-sync'
gem 'mutex_m'
gem 'pry-byebug'
gem 'rake'
gem 'rubocop'
gem 'rubocop-rake'
gem 'syslog'
gem 'test-kitchen'
