control 'azure-foundations-cis-3.3' do
    title "Ensure that 'Enable key rotation reminders' is enabled for each Storage Account"
    desc "Access Keys authenticate application access requests to data contained in Storage
        Accounts. A periodic rotation of these keys is recommended to ensure that potentially
        compromised keys cannot result in a long-term exploitable credential. The 'Rotation
        Reminder' is an automatic reminder feature for a manual procedure."

    desc 'rationale',
        "Reminders such as those generated by this recommendation will help maintain a
        regular and healthy cadence for activities which improve the overall efficacy of a
        security program.
        Cryptographic key rotation periods will vary depending on your organization's security
        requirements and the type of data which is being stored in the Storage Account. For
        example, PCI DSS mandates that cryptographic keys be replaced or rotated 'regularly,'
        and advises that keys for static data stores be rotated every 'few months.'
        For the purposes of this recommendation, 90 days will prescribed for the reminder.
        Review and adjustment of the 90 day period is recommended, and may even be
        necessary. Your organization's security requirements should dictate the appropriate
        setting."

    desc 'impact',
        "This recommendation only creates a periodic reminder to regenerate access keys.
        Regenerating access keys can affect services in Azure as well as the organization's
        applications that are dependent on the storage account. All clients that use the access
        key to access the storage account must be updated to use the new key."

    desc 'check',
       "From Azure Portal
        1. Go to Storage Accounts
        2. For each Storage Account, go to Access keys
        3. Click Set rotation reminder
        If the checkbox for Enable key rotation reminders is already checked, that Storage
        Account is compliant. Review the Remind me every field for a desirable periodic setting
        that fits your security program's needs.
        Page 189
        From Powershell
        $rgName = <resource group name for the storage>
        $accountName = <storage account name>
        $account = Get-AzStorageAccount -ResourceGroupName $rgName -Name $accountName
        Write-Output $accountName ->
        Write-Output 'Expiration Reminder set to:
        $($account.KeyPolicy.KeyExpirationPeriodInDays) Days'
        Write-Output 'Key1 Last Rotated:
        $($account.KeyCreationTime.Key1.ToShortDateString())'
        Write-Output 'Key2 Last Rotated:
        $($account.KeyCreationTime.Key2.ToShortDateString())'
        If any of the creation dates is empty, then remediation is required, due to the need of at
        least one rotation of the keys.
        If the reminder is set, the period in days will be returned. 90 days is the
        recommendation."

    desc 'fix',
       "From Azure Portal
        1. Go to Storage Accounts
        2. For each Storage Account that is not compliant, go to Access keys
        3. Click Set rotation reminder
        4. Check Enable key rotation reminders
        5. In the Send reminders field select Custom, then set the Remind me every field to
        90 and the period drop down to Days.
        6. Click Save
        From Powershell
        $rgName = <resource group name for the storage>
        $accountName = <storage account name>
        $account = Get-AzStorageAccount -ResourceGroupName $rgName -Name $accountName
        if ($account.KeyCreationTime.Key1 -eq $null -or $account.KeyCreationTime.Key2
        -eq $null){
        Write-output ('You must regenerate both keys at least once before
        setting expiration policy')
        } else {
        $account = Set-AzStorageAccount -ResourceGroupName $rgName -Name
        $accountName -KeyExpirationPeriodInDay 90
        }
        $account.KeyPolicy.KeyExpirationPeriodInDays"

    impact 0.5
    tag nist: ['CM-1','CM-2','CM-6','CM-7','CM-7(1)','CM-9','SA-3','SA-8','SA-10','SI-4']
    tag severity: 'medium'
    tag cis_controls: [{ '8' => ['4.1','13.11'] }]

    ref 'https://docs.microsoft.com/en-us/azure/storage/common/storage-create-storage-account#regenerate-storage-access-keys'
    ref 'https://learn.microsoft.com/en-us/security/benchmark/azure/mcsb-privileged-access#pa-1-separate-and-limit-highly-privilegedadministrative-users'
    ref 'https://learn.microsoft.com/en-us/security/benchmark/azure/mcsb-identity-management#im-3-manage-application-identities-securely-and-automatically'
    ref 'https://learn.microsoft.com/en-us/security/benchmark/azure/mcsb-governance-strategy#gs-6-define-and-implement-identity-and-privileged-access-strategy'
    ref 'https://learn.microsoft.com/en-us/security/benchmark/azure/mcsb-identity-management#im-8-restrict-the-exposure-of-credentials-and-secrets'
    ref 'https://www.pcidssguide.com/pci-dss-key-rotation-requirements/'
    ref 'https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-57pt1r5.pdf'

    describe 'benchmark' do
        skip 'configure'
    end
end