---
name: CIS Azure Foundations v3.0.0

on:
  push:
    branches:
      - main
      - test-pipeline
  pull_request:

jobs:
  my-job:
    name: Validate the CIS Azure Foundations v3.0.0

    runs-on: ubuntu-latest

    env:
      CHEF_LICENSE: accept-silent
      CHEF_LICENSE_KEY: ${{ secrets.SAF_CHEF_LICENSE_KEY }}
      RESULTS_FILE: azure_inspec_results.json
      THRESHOLD_FILE: inspec.threshold.yml
      INSPEC_INPUTS: ${{ secrets.INSPEC_INPUTS }}
      HEIMDALL_URL: https://heimdall-demo.mitre.org

    steps:
      - name: add needed packages
        run: sudo apt-get install -y jq curl

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Clone full repository so we can push
        run: git fetch --prune --unshallow

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Confirm git commit SHA output
        run: echo ${{ env.COMMIT_SHORT_SHA }}

      - name: Move Input file
        shell: bash
        run: |
          echo "${{ env.INSPEC_INPUTS }}" > inputs.yml

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"

      - name: Disable ri and rdoc
        run: 'echo "gem: --no-document" >> ~/.gemrc'

      - name: Bundle Install
        run: bundle install

      - name: Installed Inspec
        run: bundle exec inspec version

      - name: Vendor the InSpec Profile
        run: bundle exec inspec vendor --overwrite

      - name: Lint the Inspec profile
        run: bundle exec inspec check .

      - name: Create config json file
        run: |
          echo '{
                  "version": "1.1",
                  "cli_options": {
                    "color": "true"
                  },
                  "credentials": {
                    "pwsh": {
                      "pwsh-options": {
                        "pwsh_path": "'"${{secrets.SAF_AZURE_PWSH_PATH}}"'"
                      }
                    }
                  }
                }' > ~/.inspec/config.json

      - name: Verify config json file
        run: |
          # Print the contents of the config file
          cat ~/.inspec/config.json

      - name: Run the Profile
        run: |
          bundle exec inspec exec . --target pwsh://pwsh-options --input-file=inputs.yml --reporter cli json:${{ env.COMMIT_SHORT_SHA }}-${{ env.RESULTS_FILE }} --enhanced-outcomes --filter-empty-profiles || true

      - name: Save Test Result JSON
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.workflow }}-${{ env.COMMIT_SHORT_SHA }}-results
          path: |
            ./${{ env.COMMIT_SHORT_SHA }}-${{ env.RESULTS_FILE }}

      - name: Delete input file
        run: rm -f input_file.yml

      - name: Upload to Heimdall
        run: |
          curl -# -s -F data=@${{ env.COMMIT_SHORT_SHA }}-${{ env.RESULTS_FILE }} -F "filename=${{ env.COMMIT_SHORT_SHA }}-${{ env.RESULTS_FILE}}" -F "public=true" -F "evaluationTags=${{ env.COMMIT_SHORT_SHA }},${{ github.repository }},${{ github.workflow }}" -H "Authorization: Api-Key ${{ secrets.HEIMDALL_UPLOAD_KEY }}" "${{ env.HEIMDALL_URL }}/evaluations"

      - name: Display our ${{ env.COMMIT_SHORT_SHA }}-${{ env.RESULTS_FILE }} results summary
        uses: mitre/saf_action@v1
        with:
          command_string: "view summary -i ${{ env.COMMIT_SHORT_SHA }}-${{ env.RESULTS_FILE }}"

      - name: Ensure ${{ env.COMMIT_SHORT_SHA }}-${{ env.RESULTS_FILE }} meets our results threshold
        uses: mitre/saf_action@v1
        with:
          command_string: "validate threshold -i ${{ env.COMMIT_SHORT_SHA }}-${{ env.RESULTS_FILE }} -F ${{ env.THRESHOLD_FILE }}"
