---
name: CIS Azure Foundations v3.0.0

on:
  push:
    branches:
      - main
      - test-pipeline
  pull_request:

jobs:
  my-job:
    name: Validate the CIS Azure Foundations v3.0.0 Profile

    runs-on: ubuntu-latest

    env:
      CHEF_LICENSE: accept-silent
      CHEF_LICENSE_KEY: ${{ secrets.SAF_CHEF_LICENSE_KEY }}
      RESULTS_FILE: azure_inspec_results.json
      THRESHOLD_FILE: inspec.threshold.yml
      INSPEC_INPUTS: ${{ secrets.INSPEC_INPUTS }}
      HEIMDALL_URL: https://heimdall-demo.mitre.org

    steps:
      - name: Install Packages
        run: sudo apt-get install -y jq curl

      - name: Install Az/MgGraph Modules and Connect to Modules
        run: |
          If($null -eq (get-module -listavailable -name "az")){install-module az -Force -AllowClobber}
          If($null -eq (get-module -name "az")){import-module az}
          If($null -eq (get-module -listavailable -name "microsoft.graph")){install-module microsoft.graph -Force -AllowClobber}
          If($null -eq (get-module -name "microsoft.graph")){import-module microsoft.graph}
          $credential = New-Object System.Management.Automation.PSCredential("${{ secrets.AZURE_CLIENT_ID }}", (ConvertTo-SecureString "${{ secrets.AZURE_CLIENT_SECRET }}" -AsPlainText -Force))
          Connect-AzAccount -ServicePrincipal -TenantId "${{ secrets.AZURE_TENANT_ID }}" -Credential $credential | Out-Null
        shell: pwsh

      - name: Connect to Azure CLI
        run: |
          az login --service-principal --username "${{ secrets.AZURE_CLIENT_ID }}" --password "${{ secrets.AZURE_CLIENT_SECRET }}" --tenant "${{ secrets.AZURE_TENANT_ID }}" > /dev/null 2>&1
          az storage account list > storage_accounts.json
          cat storage_accounts.json

      - name: Check-out Repository
        uses: actions/checkout@v4

      - name: Get Full Clone of Repository
        run: git fetch --prune --unshallow

      - name: Generate Short Commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Display Short Commit SHA
        run: echo ${{ env.COMMIT_SHORT_SHA }}

      - name: Create Input File
        shell: bash
        run: |
          printf "%s" '${{ env.INSPEC_INPUTS }}' > inputs.yml

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"

      - name: Disable ri and rdoc
        run: 'echo "gem: --no-document" >> ~/.gemrc'

      - name: Install Bundle Dependencies
        run: bundle install

      - name: Check Installed Inspec Version
        run: bundle exec inspec version

      - name: Vendor the InSpec Profile
        run: bundle exec inspec vendor --overwrite

      - name: Lint Inspec profile
        run: bundle exec inspec check .

      - name: Run InSpec Profile
        run: |
          bundle exec inspec exec . \
          --input client_id=${{ secrets.AZURE_CLIENT_ID }} tenant_id=${{ secrets.AZURE_TENANT_ID }} client_secret=${{ secrets.AZURE_CLIENT_SECRET }} subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }} \
          --input-file=inputs.yml \
          --reporter cli json:${{ env.COMMIT_SHORT_SHA }}-${{ env.RESULTS_FILE }} \
          --enhanced-outcomes \
          --filter-empty-profiles

      - name: Save Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.workflow }}-${{ env.COMMIT_SHORT_SHA }}-results
          path: |
            ./${{ env.COMMIT_SHORT_SHA }}-${{ env.RESULTS_FILE }}

      - name: Delete Input file
        if: always()
        run: rm -f input_file.yml

      - name: Upload to Heimdall
        if: always()
        run: |
          curl -# -s -F data=@${{ env.COMMIT_SHORT_SHA }}-${{ env.RESULTS_FILE }} \
            -F "filename=${{ env.COMMIT_SHORT_SHA }}-${{ env.RESULTS_FILE}}" \
            -F "public=true" \
            -F "evaluationTags=${{ env.COMMIT_SHORT_SHA }},${{ github.repository }},${{ github.workflow }}" \
            -H "Authorization: Api-Key ${{ secrets.SAF_HEIMDALL_UPLOAD_KEY }}" \
            "${{ env.HEIMDALL_URL }}/evaluations"

      - name: Display ${{ env.COMMIT_SHORT_SHA }}-${{ env.RESULTS_FILE }} Results Summary
        if: always()
        uses: mitre/saf_action@v1
        with:
          command_string: "view summary -i ${{ env.COMMIT_SHORT_SHA }}-${{ env.RESULTS_FILE }}"

      - name: Ensure ${{ env.COMMIT_SHORT_SHA }}-${{ env.RESULTS_FILE }} Meets Results Threshold
        if: always()
        uses: mitre/saf_action@v1
        with:
          command_string: "validate threshold -i ${{ env.COMMIT_SHORT_SHA }}-${{ env.RESULTS_FILE }} -T ${{ env.THRESHOLD_FILE }}"
